### ISSUE TITLE
What is the status of the repo?

### ISSUE THREAD

**Issue by AshleyJBartlett** [aurelia-toolkit/aurelia-toolkit#1]
Hi @MaximBalaganskiy ,

I am trying to use this plugin as you suggested. However, I am struggling to make it work and I think its down to a combination of missing documentation/examples and the package missing exports and dependencies.

Please can you provide an example of where you have it working? Maybe create a CodePen or something.

Many thanks,
Ash

**Comment by MaximBalaganskiy** [comment]
The question is about the datepicker, right?
I don't package compiled SASS and therefore it is impossible at the moment to make it work in a gist due to js sass module limitation. 

You have to have ALL THE peer dependencies installed. On top of that `aurelia-inputmask` and `@aurelia-toolkit/mdc-inputmask` are required.

The setup is as follows
```ts
  aurelia.use
    .standardConfiguration()
    .plugin(PLATFORM.moduleName('aurelia-inputmask'), { showMaskOnHover: false })
    .plugin(PLATFORM.moduleName('@aurelia-mdc-web/all'))
    .plugin(PLATFORM.moduleName('@aurelia-toolkit/mdc-inputmask'))
    .plugin(PLATFORM.moduleName('@aurelia-toolkit/mdc-datepicker'), (c: MdcDatepickerDialogConfiguration) => {
      c.defaultOptions.i18n.dateFnsLocale = enAU;
      c.defaultOptions.firstDay = 1;
    });
```

Somewhere in your styles
```sass
@use "@aurelia-toolkit/mdc-datepicker";
```

This is not consumer friendly, I know, but this is due to the complexity of the task. That is why this is a "half-private" package which I don't advertise much.

**Comment by MaximBalaganskiy** [comment]
aurelia-inputmask is needed to mask the input field, mdc-inputmask - adapts the previous to the MDC  bridge, date-dns - for date functions

**Comment by AshleyJBartlett** [comment]
Thank you for getting back to me. I have been able to implement this now so this issue can be closed.

I have also just created a [PR](https://github.com/aurelia-toolkit/aurelia-toolkit/pull/2) for this repo.
